Repository buildingSMART/Sample-Test-Files, pull requests merged in 2020-11, with the labels that each got.

#49 Improving TIN_4
  IFC 4.3/Georeferencing_Tiny_Tin_2/readme.md
  IFC 4.3/Tin_4/UT_Tin_4.ifc
  IFC 4.3/Tin_4/UT_Tin_4_1.png
  IFC 4.3/Tin_4/UT_Tin_4_2.png
  IFC 4.3/Tin_4/readme.md
Labels: enhancement, infra depl

#44 Improved Tin_1 unit test
  IFC 4.3/Georeferencing_1/UT_GeoRef_1.ifc
  IFC 4.3/Georeferencing_1/readme.md
  IFC 4.3/Tin_1/UT_Tin_1.ifc
  IFC 4.3/Tin_1/UT_Tin_1_1.PNG
  IFC 4.3/Tin_1/UT_Tin_1_2.png
  IFC 4.3/Tin_1/readme.md
Labels: enhancement, infra depl

#55 Expanded unit test template to optionally include a storyline reference.
  IFC 4.3/UnitTestTemplate.md
Labels: documentation, infra depl

#45 Improving tin2
  IFC 4.3/Small_Tin_1/readme.md
  IFC 4.3/Tin_2/UT_Tin_2.ifc
  IFC 4.3/Tin_2/UT_Tin_2_1.png
  IFC 4.3/Tin_2/UT_Tin_2_2.png
  IFC 4.3/Tin_2/readme.md
Labels: enhancement, infra depl

#48 Updating TIN_3
  IFC 4.3/Georeferencing_Tiny_Tin_1/UT_tiny_tin_in_MGA_56_old.ifc
  IFC 4.3/Georeferencing_Tiny_Tin_1/readme.md
  IFC 4.3/Tin_3/UT_Tin_3.ifc
  IFC 4.3/Tin_3/UT_Tin_3_1.png
  IFC 4.3/Tin_3/UT_Tin_3_2.png
  IFC 4.3/Tin_3/readme.md
Labels: enhancement, infra depl

#62 New UT for SpatialStructure (Level crossing)
  IFC 4.3/SpatialStructure_3/Figure 1 - situation.png
  IFC 4.3/SpatialStructure_3/Figure 2 - result.png
  IFC 4.3/SpatialStructure_3/IFCTreeView.PNG
  IFC 4.3/SpatialStructure_3/SpatialStructure_3.ifc
  IFC 4.3/SpatialStructure_3/readme.md
Labels: infra depl
